### ISSUE TITLE
Can't download libavXXXX-ffmpeg56 on Raspbian

### ISSUE THREAD

**Issue by Katsuryoku** [deepch/RTSPtoImage#1]
We can't download libavXXXX-ffmpeg56 on Raspbian (raspberry debian linux). 
It-is possible to link it with another lib or to change github.com/deepch/vdk/cgo/ffmpeg ?

`# github.com/deepch/vdk/cgo/ffmpeg`
`In file included from /home/pi/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210508200759-5adbbcc01f89/cgo/ffmpeg/audio.go:4:`
`./ffmpeg.h:5:10: fatal error: libavresample/avresample.h: No such file or directory`
` #include <libavresample/avresample.h>`
`          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`compilation terminated.`

**Comment by deepch** [comment]
need install avresample dev over apt install
